import type { Finding, ScannerType } from '../types/index.ts';

const MOCK_FINDINGS: Array<{
  scanner: ScannerType;
  file: string;
  policyId: string;
  policyName: string;
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  resource: string;
  description: string;
  remediation: string;
  framework: 'terraform' | 'kubernetes' | 'dockerfile' | 'helm';
  complianceIds: string[];
}> = [
  {
    scanner: 'checkov',
    file: 'fixtures/terraform/s3.tf',
    policyId: 'CKV_AWS_18',
    policyName: 'S3 bucket has public ACL configured',
    severity: 'HIGH',
    resource: 'aws_s3_bucket.public_bucket',
    description: 'S3 Bucket has a public ACL configured which allows anyone to read objects in the bucket.',
    remediation: 'Remove the ACL block or set acl to "private". Consider using S3 Block Public Access.',
    framework: 'terraform',
    complianceIds: ['CIS-3.3', 'PCI-1.2'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/terraform/s3.tf',
    policyId: 'CKV_AWS_20',
    policyName: 'S3 Bucket does not have SSE-S3 encryption enabled',
    severity: 'MEDIUM',
    resource: 'aws_s3_bucket.unencrypted_bucket',
    description: 'S3 Bucket does not have server-side encryption (SSE) enabled.',
    remediation: 'Add a server_side_encryption_configuration block with sse_algorithm = "AES256" or "aws:kms".',
    framework: 'terraform',
    complianceIds: ['CIS-3.4', 'NIST-SI-12'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/terraform/security_group.tf',
    policyId: 'CKV_AWS_24',
    policyName: 'Security group allows 0.0.0.0/0 ingress on port 22',
    severity: 'CRITICAL',
    resource: 'aws_security_group.open_ssh',
    description: 'Security group rule allows ingress from 0.0.0.0/0 on port 22 (SSH).',
    remediation: 'Restrict ingress to specific IP ranges. Avoid 0.0.0.0/0 for administrative ports.',
    framework: 'terraform',
    complianceIds: ['CIS-3.7', 'NIST-AC-3'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/terraform/security_group.tf',
    policyId: 'CKV2_AWS_6',
    policyName: 'Security group allows 0.0.0.0/0 ingress on port 3389',
    severity: 'HIGH',
    resource: 'aws_security_group.open_rdp',
    description: 'Security group rule allows ingress from 0.0.0.0/0 on port 3389 (RDP).',
    remediation: 'Restrict RDP access to specific IP ranges or use VPN/SSH tunneling.',
    framework: 'terraform',
    complianceIds: ['CIS-3.8'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/terraform/main.tf',
    policyId: 'CKV_AWS_21',
    policyName: 'S3 Bucket does not have versioning enabled',
    severity: 'LOW',
    resource: 'aws_s3_bucket.main',
    description: 'S3 Bucket does not have versioning enabled to protect against accidental deletion.',
    remediation: 'Add versioning { enabled = true } block to the S3 bucket resource.',
    framework: 'terraform',
    complianceIds: ['CIS-3.5', 'PCI-1.3'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/kubernetes/pod.yaml',
    policyId: 'CKV_K8S_1',
    policyName: 'Container runs as privileged',
    severity: 'HIGH',
    resource: 'Pod.privileged-pod',
    description: 'Container is running with privileged security context, granting elevated capabilities.',
    remediation: 'Set securityContext.privileged to false and drop ALL capabilities.',
    framework: 'kubernetes',
    complianceIds: ['CIS-5.1', 'NIST-SC-4'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/kubernetes/pod.yaml',
    policyId: 'CKV_K8S_2',
    policyName: 'Container runs as root user',
    severity: 'MEDIUM',
    resource: 'Pod.privileged-pod',
    description: 'Container is running as root user without runAsNonRoot: true.',
    remediation: 'Set securityContext.runAsNonRoot: true and runAsUser to a non-zero value.',
    framework: 'kubernetes',
    complianceIds: ['CIS-5.2'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/kubernetes/pod.yaml',
    policyId: 'CKV_K8S_3',
    policyName: 'Container has no resource limits',
    severity: 'MEDIUM',
    resource: 'Pod.privileged-pod',
    description: 'Container does not have resource limits defined, which could lead to resource exhaustion.',
    remediation: 'Add resources.limits and resources.requests for CPU and memory.',
    framework: 'kubernetes',
    complianceIds: ['CIS-5.3'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/kubernetes/pod.yaml',
    policyId: 'CKV_K8S_4',
    policyName: 'Container has allowPrivilegeEscalation enabled',
    severity: 'HIGH',
    resource: 'Pod.privileged-pod',
    description: 'Container has allowPrivilegeEscalation not set to false.',
    remediation: 'Set securityContext.allowPrivilegeEscalation to false.',
    framework: 'kubernetes',
    complianceIds: ['CIS-5.4'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/docker/Dockerfile',
    policyId: 'CKV_DOCKER_1',
    policyName: 'Dockerfile uses root user',
    severity: 'MEDIUM',
    resource: 'Dockerfile',
    description: 'Dockerfile does not specify a non-root user. Container will run as root by default.',
    remediation: 'Add a USER directive to run as a non-root user. Create a user with useradd if needed.',
    framework: 'dockerfile',
    complianceIds: ['PCI-4.2', 'NIST-CM-6'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/docker/Dockerfile',
    policyId: 'CKV_DOCKER_2',
    policyName: 'Dockerfile uses latest tag',
    severity: 'LOW',
    resource: 'Dockerfile',
    description: 'Base image uses "latest" tag which can lead to unpredictable builds and security updates.',
    remediation: 'Pin a specific version tag for the base image. Avoid using :latest.',
    framework: 'dockerfile',
    complianceIds: ['CIS-4.1', 'NIST-SI-12'],
  },
  {
    scanner: 'checkov',
    file: 'fixtures/docker/Dockerfile',
    policyId: 'CKV_DOCKER_3',
    policyName: 'Dockerfile does not clean apt cache',
    severity: 'LOW',
    resource: 'Dockerfile',
    description: 'apt-get install does not include cleanup of cache files, increasing image size.',
    remediation: 'Chain rm -rf /var/lib/apt/lists/* after apt-get install to clean the cache.',
    framework: 'dockerfile',
    complianceIds: ['CIS-4.2'],
  },
  {
    scanner: 'trivy',
    file: 'fixtures/terraform/s3.tf',
    policyId: 'AVD-AWS-0137',
    policyName: 'S3 bucket has public ACL configured',
    severity: 'HIGH',
    resource: 'aws_s3_bucket.public_bucket',
    description: 'S3 Bucket has a public ACL configured.',
    remediation: 'Set acl to private or use aws_s3_bucket_public_access_block.',
    framework: 'terraform',
    complianceIds: ['CIS-3.3', 'PCI-1.2'],
  },
  {
    scanner: 'trivy',
    file: 'fixtures/terraform/security_group.tf',
    policyId: 'AVD-AWS-0126',
    policyName: 'Security group allows ingress from 0.0.0.0/0 on SSH',
    severity: 'CRITICAL',
    resource: 'aws_security_group.open_ssh',
    description: 'Security group rule allows unrestricted SSH access.',
    remediation: 'Restrict SSH to specific IP ranges.',
    framework: 'terraform',
    complianceIds: ['CIS-3.7', 'NIST-AC-3'],
  },
  {
    scanner: 'trivy',
    file: 'fixtures/kubernetes/pod.yaml',
    policyId: 'AVD-KSV-0001',
    policyName: 'Container allows privilege escalation',
    severity: 'MEDIUM',
    resource: 'Pod.privileged-pod',
    description: 'Container allows privilege escalation.',
    remediation: 'Set allowPrivilegeEscalation to false.',
    framework: 'kubernetes',
    complianceIds: ['CIS-5.4'],
  },
];

export function getMockFindings(scanId: string): Finding[] {
  const now = new Date().toISOString();
  return MOCK_FINDINGS.map((f, i) => ({
    ...f,
    id: `${scanId}-mock-${i}`,
    scanId,
    exceptionId: null,
    createdAt: now,
  }));
}

export function getDemoDirectory(): string {
  return 'fixtures';
}
